In [8]:
import pandas as pd

df = pd.read_csv("../Data/1.normalized_dataset.csv")
df

,target,id,date,flag,user,text,text_token
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,awww thats bummer you shoulda got david carr ...,"['awww', 'thats', 'bummer', 'shoulda', 'get', ..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he cant update his facebook by t...,"['upset', 'cant', 'update', 'facebook', 'texti..."
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,dived many times for the ball managed to save...,"['dive', 'many', 'time', 'ball', 'manage', 'sa..."
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,"['whole', 'body', 'feel', 'itchy', 'like', 'fi..."
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,no its not behaving at all im mad why am here ...,"['behaving', 'im', 'mad', 'cant', 'see']"
...,...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,just woke up having no school is the best feel...,"['woke', 'school', 'best', 'feel', 'ever']"
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,thewdbcom very cool to hear old walt interviews,"['thewdbcom', 'cool', 'hear', 'old', 'walt', '..."
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,are you ready for your mojo makeover ask me fo...,"['ready', 'mojo', 'makeover', 'ask', 'detail']"
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,happy th birthday to my boo of alll time tupac...,"['happy', 'th', 'birthday', 'boo', 'alll', 'ti..."
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy charitytuesday,"['happy', 'charitytuesday']"

In [9]:
import ast
import re

array_list = df['text_token'].values
data_list = []
for item in array_list:
    data_list.append(ast.literal_eval(item))

result = []
for lists in data_list:
    new_list = []
    for value in lists:
        new_value = re.sub(r'\d', '', value)
        new_list.append(new_value)
    result.append(new_list)

df_list = pd.DataFrame({'text_token': result})
df = df.drop(columns=['text_token'])
df['text_token'] = df_list['text_token']
df['words'] = df['text_token'].apply(lambda x: ' '.join(x))
df = df.drop(columns=['text_token'])
df

,target,id,date,flag,user,text,words
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,awww thats bummer you shoulda got david carr ...,awww thats bummer shoulda get david carr third...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he cant update his facebook by t...,upset cant update facebook texting might cry r...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,dived many times for the ball managed to save...,dive many time ball manage save rest go bound
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole body feel itchy like fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,no its not behaving at all im mad why am here ...,behaving im mad cant see
...,...,...,...,...,...,...,...
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,just woke up having no school is the best feel...,woke school best feel ever
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,thewdbcom very cool to hear old walt interviews,thewdbcom cool hear old walt interview
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,are you ready for your mojo makeover ask me fo...,ready mojo makeover ask detail
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,happy th birthday to my boo of alll time tupac...,happy th birthday boo alll time tupac amaru sh...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy charitytuesday,happy charitytuesday

In [10]:
word_dataset = '../Data/2.cleaned_dataset.csv'
df.to_csv(word_dataset, index=False)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_Cv = vectorizer.fit_transform(df['words'])
y_Cv = df['target']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_Cv, y_Cv, test_size = 0.4, random_state = 42)

In [6]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(solver="liblinear")
logistic_model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [7]:
from sklearn.metrics import accuracy_score

y_pred = logistic_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7769109375